<?php
 function comment_buddy(){
   $comment = array();
   $comment['comment'] = array(
     'title' => 'comment',
     'page callback' => custom_submit_function,
     'access callback' => TRUE,
     'type' => MENU_CALLBACK,
   );
 }

 // function display_comment()
 // {
 //   return '<h1> hello </h1>';
 // }
function custom_form_comment_form_alter(&$form, &$form_state){
  $form['#after_build'][] = 'custom_afterbuild_function';
}

 function custom_afterbuild_function($form, &$form_state) {
  $form['#submit'][] = 'custom_submit_function';
}

 function custom_submit_function($form, &$form_state) {
  drupal_set_message('Comment commented');
 }
