<?php

 function comment_buddy_menu(){
   $items = array();
   $items['comments_add'] = array(
     'title' => 'New Message',
     'page callback' => 'add_comments',
     'access callback' => TRUE,
     'type' => MENU_CALLBACK,
   );
   return $items;
 }


 function add_comments(){
   drupal_set_message('Comment commented');
   return '<p>Thank you for your comment</p>';
 }

 function comment_buddy_comment_insert(){
   $_GET['destination'] = 'comments_add';
 }
